INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (1, N'預拌混凝土(280kgf/cm2, 飛灰爐石替代率30%)', N'm³', 301)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (2, N'預拌混凝土(280kgf/cm2, 飛灰爐石替代率50%)', N'm³', 214)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (3, N'預拌混凝土(350kgf/cm2, 飛灰爐石替代率30%)', N'm³', 341)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (4, N'預拌混凝土(350kgf/cm2, 飛灰爐石替代率50%)', N'm³', 244)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (5, N'預拌混凝土(140 kgf/cm2)', N'm³', 200)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (6, N'預拌混凝土(175 kgf/cm2)', N'm³', 224)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (7, N'預拌混凝土(210 kgf/cm2)', N'm³', 238)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (8, N'預拌水中混凝土(210 kgf/cm2)', N'm³', 346)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (9, N'預拌混凝土(245 kgf/cm2)', N'm³', 252)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (10, N'預拌混凝土(280 kgf/cm2)', N'm³', 338)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (11, N'自充填預拌混凝土(350 kgf/cm2)', N'm³', 375)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (12, N'卜特蘭水泥(II型)', N'kg', 0.981)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (13, N'卜特蘭水泥(II型)', N'kg', 0.964)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (14, N'鋁質水泥', N'kg', 10.1)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (15, N'水泥熟料', N'kg', 0.948)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (16, N'水泥(不分型號)', N'kg', 0.907)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (17, N'水泥熟料', N'kg', 0.95)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (18, N'卜特蘭水泥(乾式)', N'kg', 0.94)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (19, N'鋼筋混凝土用鋼筋(SD280W)', N'kg', 0.835)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (20, N'鋼筋混凝土用鋼筋(SD420W)', N'kg', 0.834)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (21, N'牆面石材', N'm²', 15.11)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (22, N'牆面磁磚', N'm²', 19.1)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (23, N'地坪類磁磚', N'm²', 25.16)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (24, N'地坪類實木地板', N'm²', 9.08)
INSERT INTO [dbo].[carbon] ([Id], [name], [unit], [kgCO2e]) VALUES (25, N'裝修玻璃 - 合成', N'kg', 0.75318)
